spring.application.name=SalesforceContextGraph

server.port=8081

spring.datasource.username=root
spring.datasource.password=Mysql@2002
spring.datasource.url=jdbc:mysql://localhost:3306/autorabit_salesforce_context_graph
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

salesforce.fetch-mode=live
salesforce.login-url=${SALESFORCE_LOGIN_URL:https://orgfarm-f90b1a99a1-dev-ed.develop.my.salesforce.com}
salesforce.client-id=${SALESFORCE_CLIENT_ID:3MVG97L7PWbPq6UwSwyY8vtcGcgY7WXWMDcXwg4dWVnai_JVPsP.vs7ppCYMpNuu8HKl01_h6NAlmYIvXQdhP}
salesforce.client-secret=${SALESFORCE_CLIENT_SECRET:235F28D4E2BF8B25002659983F0A1C0C184E16982F7099086065E5ABCB02D3B8}
salesforce.api-version=${SALESFORCE_API_VERSION:v65.0}

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3.5:397b-cloud